[package]
name = "aij-judgend"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-http = { version = "0.6.11", features = ["trace"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
tracing-appender = "0.2.4"
tokio = { version = "1.52.3", features = ["full"] }
axum = { version = "0.8.9", features = ["multipart"] }
judger = "0.6.2"
serde_json = "1.0.149"
reqwest = { version = "0.13.3", features = ["json"] }
regex = "1.12.2"
tokio-util = "0.7.18"
which = "8.0.0"
toml = "1.0.4"
serde_yaml = "0.9"
zip = "8.6.0"
tempfile = "3.26.0"
futures-util = "0.3.32"
config = "0.15.23"
strum = { version = "0.28.0", features = ["derive"] }
libc = "0.2"
[dev-dependencies]
axum-test = "20.0.0"
serial_test = "3.4.0"
