[problem_info]
problem_type = "interactive"
checker_type = "interactor"
time_limit_ms = 1000
memory_limit_kb = 256000

[testcases."1"]
in_path = "1.in"
ans_path = "1.ans"
weight = 1.0

[testcases."2"]
in_path = "2.aaa"
ans_path = "2.bbb"
weight = 1.0

[subtasks."1"]
cases = ["1", "2"]
pre_subtasks = []
score = 100
type = "min"

[custom_modules]
interactor_path = "interactor.cpp"