[problem_info]
problem_type = "interactive"
checker_type = "interactor"
time_limit_ms = 1000
memory_limit_kb = 256000

[[testcases]]
id = 1
in_path = "1.in"
ans_path = "1.ans"
weight = 1.0

[[testcases]]
id = 2
in_path = "2.aaa"
ans_path = "2.bbb"
weight = 1.0


[custom_modules]
interactor_path = "interactor.cpp"